// Not in the public repository.
//
// The private bondli repository carries a multi-wallet "fleet" trader behind the legacy /api/session
// and /api/fleet routes of the production server. It is not part of the hosted bot, which excludes
// fleet wallets and manufactured volume by constraint (src/velocity/README.md), and it is not
// published. This stub keeps src/api/server.production.mjs importable: every route that reaches it
// answers that the feature is unavailable. Generated by tools/sync-public.mjs in the private repo.
const UNAVAILABLE = "fleet trading is not part of the public repository";
const unavailable = () => { throw new Error(UNAVAILABLE); };

export class FleetTrader {
  constructor() { this.sessions = new Map(); }
  async launch() { unavailable(); }
  command() { return { ok: false, error: UNAVAILABLE }; }
  async close() { unavailable(); }
  async recover() { unavailable(); }
  async sellFromWallet() { unavailable(); }
  async getWalletBalances() { return []; }
  status() { return { sessions: {}, activeSessions: 0 }; }
  getSessionStatus() { return null; }
}

export async function skimSweep() { unavailable(); }
