#!/usr/bin/env node
// ═══ sync-public: build the public mirror of this repository ═══
//
//   node tools/sync-public.mjs --to ../Bondli_public [--dry]
//
// The public repository (github.com/Bradbuythedip/Bondli_public) is this one minus a short, named
// exclusion list. Everything else is copied verbatim, so `npm test` there runs the same suite a
// reviewer would run here. This file is the whole definition of what is public: a file that is not
// excluded below is published the next time the script runs, so add to the list before adding a
// secret-bearing or operator-only file to the tree.
//
// Left out, and why:
//   launch/, GAME_THEORY.md, tests/robinhood/, tests/launch/
//       operator tooling for launching a token with a fleet of wallets, with its docs and tests. Not
//       part of the product (nothing under src/, app/ or deploy/ imports it) and not published.
//   src/engine/{fleet-trader,fleet-brains,volume-engine,launch-orchestrator,anti-detection,
//               orchestrator,exit,recover,wallet-optimizer,wallet-saver}.mjs, src/api/server.mjs
//       the pump.fun fleet engine and the legacy dev server that drove it. The hosted bot excludes
//       fleet wallets and manufactured volume by constraint (src/velocity/README.md); so does the
//       mirror. fleet-trader.mjs is replaced by a stub so the production server still boots and
//       the legacy routes that reach it answer that the feature is unavailable.
//   docs/audit/
//       the adversarial audit journal. It lists open findings against a live service with money in
//       it; the findings that were fixed are summarised in docs/GRANT-ARC.md, which is published.
//
// Everything else is published, README and documentation included: `docs/` is owned by the mirror,
// so a document that is not in this repository's docs/ does not survive there.
//
// Transformed, each behind an assertion so a change on this side fails the sync instead of drifting:
//   src/engine/config.mjs   the fleet's volume/auto-rug keys and wallet roles are dropped (nothing
//                           published reads them; the sync verifies that)
//   package.json            scripts that point at excluded files are dropped; the test glob loses
//                           the excluded suites; the repository field names the public repo
//   deploy/Dockerfile       boots the production server (the dev server is not published)
//   docs/AXIOMS.md          one operations note about credential rotation is dropped
//
// Nothing here is a substitute for not committing secrets: the script copies what git tracks.

import fs from "node:fs";
import path from "node:path";
import { execFileSync } from "node:child_process";
import { fileURLToPath } from "node:url";

const SRC = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const PUBLIC_REPO = "https://github.com/Bradbuythedip/Bondli_public";

const args = process.argv.slice(2);
const dry = args.includes("--dry");
const toIdx = args.indexOf("--to");
if (toIdx < 0 || !args[toIdx + 1]) {
  console.error("usage: node tools/sync-public.mjs --to <public checkout> [--dry]");
  process.exit(2);
}
const DEST = path.resolve(args[toIdx + 1]);
if (!fs.existsSync(path.join(DEST, ".git"))) {
  console.error(`${DEST} is not a git checkout; refusing to write into it`);
  process.exit(2);
}

// ── What stays private ──
const EXCLUDE_PREFIXES = ["launch/", "docs/audit/", "tests/robinhood/", "tests/launch/"];
const EXCLUDE_FILES = new Set([
  "GAME_THEORY.md",
  "src/api/server.mjs",
  "src/engine/fleet-brains.mjs",
  "src/engine/volume-engine.mjs",
  "src/engine/launch-orchestrator.mjs",
  "src/engine/anti-detection.mjs",
  "src/engine/orchestrator.mjs",
  "src/engine/exit.mjs",
  "src/engine/recover.mjs",
  "src/engine/wallet-optimizer.mjs",
  "src/engine/wallet-saver.mjs",
]);

// ── What is replaced by a stub ──
const STUBS = {
  "src/engine/fleet-trader.mjs": `// Not in the public repository.
//
// The private bondli repository carries a multi-wallet "fleet" trader behind the legacy /api/session
// and /api/fleet routes of the production server. It is not part of the hosted bot, which excludes
// fleet wallets and manufactured volume by constraint (src/velocity/README.md), and it is not
// published. This stub keeps src/api/server.production.mjs importable: every route that reaches it
// answers that the feature is unavailable. Generated by tools/sync-public.mjs in the private repo.
const UNAVAILABLE = "fleet trading is not part of the public repository";
const unavailable = () => { throw new Error(UNAVAILABLE); };

export class FleetTrader {
  constructor() { this.sessions = new Map(); }
  async launch() { unavailable(); }
  command() { return { ok: false, error: UNAVAILABLE }; }
  async close() { unavailable(); }
  async recover() { unavailable(); }
  async sellFromWallet() { unavailable(); }
  async getWalletBalances() { return []; }
  status() { return { sessions: {}, activeSessions: 0 }; }
  getSessionStatus() { return null; }
}

export async function skimSweep() { unavailable(); }
`,
};

// ── What is rewritten on the way out ──
const must = (cond, what) => { if (!cond) throw new Error(`sync-public: ${what}; update tools/sync-public.mjs to match the source`); };
const findOnce = (lines, pred, what) => {
  const hits = lines.map((l, i) => (pred(l) ? i : -1)).filter(i => i >= 0);
  must(hits.length === 1, `${what}: expected exactly one match, found ${hits.length}`);
  return hits[0];
};

const TRANSFORMS = {
  "src/engine/config.mjs": (text) => {
    const lines = text.split("\n");
    must(lines[0].includes(" + Volume Engine"), "config.mjs header no longer names the volume engine");
    lines[0] = lines[0].replace(" + Volume Engine", "");
    const a = findOnce(lines, l => l.trim().startsWith("// Volume engine"), "config.mjs volume-engine block");
    const b = findOnce(lines, l => l.trim().startsWith("// Bags.fm integration"), "config.mjs bags block");
    must(b > a, "config.mjs: bags block should follow the volume block");
    lines.splice(a, b - a);
    lines.splice(findOnce(lines, l => l.includes("PURGE_PERCENT:"), "config.mjs PURGE_PERCENT"), 1);
    const w = findOnce(lines, l => l.startsWith("export const WALLET_ROLES"), "config.mjs WALLET_ROLES");
    const d = findOnce(lines, l => l.startsWith("export default CONFIG"), "config.mjs default export");
    must(d > w, "config.mjs: default export should follow WALLET_ROLES");
    lines.splice(w, d - w);
    const out = lines.join("\n");
    must(!/AUTO_RUG|VOLUME_|WALLET_ROLES|PHASES|getWalletCount|PURGE_PERCENT/.test(out), "config.mjs still carries fleet keys after the transform");
    return out;
  },
  "package.json": (text) => {
    const pkg = JSON.parse(text);
    for (const k of ["dry", "exit", "exit:dry", "recover", "recover:execute", "fleet", "fleet:sim", "fleet:test"]) {
      must(k in pkg.scripts, `package.json script "${k}" missing`);
      delete pkg.scripts[k];
    }
    must(pkg.scripts["api:dev"] === "node src/api/server.mjs", "package.json api:dev changed");
    pkg.scripts["api:dev"] = "node src/api/server.production.mjs";
    must(pkg.scripts.test.includes("tests/robinhood/*.test.mjs") && pkg.scripts.test.includes("tests/launch/*.test.mjs"), "package.json test glob changed");
    pkg.scripts.test = pkg.scripts.test.replace(" tests/robinhood/*.test.mjs", "").replace(" tests/launch/*.test.mjs", "");
    pkg.repository = { type: "git", url: PUBLIC_REPO };
    return JSON.stringify(pkg, null, 2) + "\n";
  },
  "deploy/Dockerfile": (text) => {
    must(text.includes('CMD ["node", "src/api/server.mjs"]'), "Dockerfile CMD changed");
    return text.replace('CMD ["node", "src/api/server.mjs"]', 'CMD ["node", "src/api/server.production.mjs"]');
  },
  "docs/AXIOMS.md": (text) => {
    const lines = text.split("\n");
    const i = findOnce(lines, l => l.startsWith("- Exposed credentials"), "AXIOMS.md credential-rotation note");
    let n = 1;
    while (i + n < lines.length && lines[i + n].startsWith("  ")) n++;
    lines.splice(i, n);
    return lines.join("\n");
  },
};

// ── The mirror owns the whole checkout: any file this run did not write is removed, so a file
//    deleted here disappears there too and the two trees cannot silently diverge. `.git`,
//    `node_modules` and `dist` are never touched.
const MIRRORED_ROOT = ".";

// ── The manifest: what git tracks here, minus the exclusions ──
const tracked = execFileSync("git", ["ls-files", "-z"], { cwd: SRC, encoding: "utf8" }).split("\0").filter(Boolean);
const excluded = (rel) => EXCLUDE_FILES.has(rel) || EXCLUDE_PREFIXES.some(p => rel.startsWith(p));
const manifest = tracked.filter(rel => !excluded(rel));
const excludedSet = new Set(tracked.filter(excluded));

for (const rel of Object.keys(STUBS)) must(tracked.includes(rel), `stubbed file ${rel} is not tracked`);
for (const rel of Object.keys(TRANSFORMS)) must(manifest.includes(rel), `transformed file ${rel} is not in the manifest`);

// ── No published module may import an excluded one (a stub counts as published) ──
const IMPORT_RE = /(?:import|export)[^'"]*?from\s*['"](\.[^'"]+)['"]|import\(\s*['"](\.[^'"]+)['"]\s*\)|^\s*import\s*['"](\.[^'"]+)['"]/gm;
const leaks = [];
for (const rel of manifest) {
  if (!/\.(mjs|js|jsx)$/.test(rel) || rel in STUBS) continue;
  const src = fs.readFileSync(path.join(SRC, rel), "utf8");
  for (const m of src.matchAll(IMPORT_RE)) {
    const spec = m[1] || m[2] || m[3];
    let target = path.normalize(path.join(path.dirname(rel), spec));
    if (!tracked.includes(target)) { const alt = [".mjs", ".js", "/index.mjs", "/index.js"].map(e => target + e).find(t => tracked.includes(t)); if (alt) target = alt; }
    if (excludedSet.has(target)) leaks.push(`${rel} -> ${target}`);
  }
}
must(leaks.length === 0, `published files import excluded ones:\n  ${leaks.join("\n  ")}`);

// ── Write ──
const written = new Set();
let copied = 0, transformed = 0, stubbed = 0;
const emit = (rel, content) => {
  const dest = path.join(DEST, rel);
  written.add(rel);
  if (dry) return;
  fs.mkdirSync(path.dirname(dest), { recursive: true });
  if (content == null) fs.copyFileSync(path.join(SRC, rel), dest);
  else fs.writeFileSync(dest, content);
  const mode = fs.statSync(path.join(SRC, rel)).mode;
  fs.chmodSync(dest, mode & 0o777);
};

for (const rel of manifest) {
  if (rel in STUBS) continue;
  if (rel in TRANSFORMS) { emit(rel, TRANSFORMS[rel](fs.readFileSync(path.join(SRC, rel), "utf8"))); transformed++; }
  else { emit(rel, null); copied++; }
}
for (const [rel, body] of Object.entries(STUBS)) { emit(rel, body); stubbed++; }

// Every transformed or stubbed module must still parse.
if (!dry) {
  for (const rel of [...Object.keys(TRANSFORMS), ...Object.keys(STUBS)]) {
    if (!/\.(mjs|js)$/.test(rel)) continue;
    execFileSync(process.execPath, ["--check", path.join(DEST, rel)], { stdio: "inherit" });
  }
}

// Remove what the mirror owns and this run did not write.
let removed = 0;
const walk = (dir) => {
  if (!fs.existsSync(dir)) return;
  for (const ent of fs.readdirSync(dir, { withFileTypes: true })) {
    if (ent.name === "node_modules" || ent.name === "dist" || ent.name === ".git") continue;
    const abs = path.join(dir, ent.name);
    if (ent.isDirectory()) { walk(abs); if (!dry && fs.readdirSync(abs).length === 0) fs.rmdirSync(abs); continue; }
    const rel = path.relative(DEST, abs).split(path.sep).join("/");
    if (!written.has(rel)) { removed++; console.log(`  - ${rel}`); if (!dry) fs.unlinkSync(abs); }
  }
};
walk(path.join(DEST, MIRRORED_ROOT));

console.log(`${dry ? "[dry] " : ""}${copied} copied, ${transformed} transformed, ${stubbed} stubbed, ${removed} removed, ${excludedSet.size} excluded -> ${DEST}`);
console.log("excluded:");
for (const rel of [...excludedSet].sort()) console.log(`  ${rel}`);
